### ISSUE TITLE
Cannnot Get StreamStatus

### ISSUE THREAD

**Issue by Parfaitomcat** [tinodo/obsclient#2] opened 2023-10-01 06:39 UTC
I have One（１） trouble  on ObsClient 

After failing to connect to Stream Server with OBS, Connection Timeout occurs when OBSClient GetStreamStatus() method is called.
This problem persists until OBS is restarted.

**Comment by Parfaitomcat** [comment] 2023-10-15 07:55
self follow

As a result of analyzing the above problem, it was found that the JSON syntax shown below differs depending on whether OBS was able to connect to the streaming server or not.

According to the OBS-WebSocket protocol sheet, this syntax is non-nullable.
On the other hand, since null is actually assigned, it is thought that an error occurred when parsing the JSON syntax.

GetStreamStatus( )
incorrect data
:21:39.024:   "d": {
10:21:39.024:     "requestData": null,
10:21:39.024:     "requestId": "bef203bd-4a40-4a9b-bac8-a5b1af1ea86e",
10:21:39.024:     "requestType": "GetStreamStatus"
10:21:39.024:   },
10:21:39.024:   "op": 6
10:21:39.024: }
10:21:39.024: [obs-websocket] [debug] [WebSocketServer::onMessage] Outgoing message:
10:21:39.024: {
10:21:39.024:   "d": {
10:21:39.024:     "requestId": "bef203bd-4a40-4a9b-bac8-a5b1af1ea86e",
10:21:39.024:     "requestStatus": {
10:21:39.024:       "code": 100,
10:21:39.024:       "result": true
10:21:39.024:     },
10:21:39.024:     "requestType": "GetStreamStatus",
10:21:39.024:     "responseData": {
10:21:39.024:       "outputActive": false,
10:21:39.024:       "outputBytes": 0,
**10:21:39.024:       "outputCongestion": null,**
10:21:39.024:       "outputDuration": 0,
10:21:39.024:       "outputReconnecting": false,
10:21:39.024:       "outputSkippedFrames": 0,
10:21:39.024:       "outputTimecode": "00:00:00.000",
10:21:39.024:       "outputTotalFrames": 0
10:21:39.024:     }
10:21:39.024:   },
10:21:39.024:   "op": 7
10:21:39.024: } 

Normal data
12:55:12.264: [obs-websocket] [debug] [WebSocketServer::onMessage] Incoming message (decoded):
12:55:12.264: {
12:55:12.264:   "d": {
12:55:12.264:     "requestData": null,
12:55:12.264:     "requestId": "5c3cbc12-438e-4e52-8438-9a1c633ceb0b",
12:55:12.264:     "requestType": "GetStreamStatus"
12:55:12.264:   },
12:55:12.264:   "op": 6
12:55:12.264: }
12:55:12.265: [obs-websocket] [debug] [WebSocketServer::onMessage] Outgoing message:
12:55:12.265: {
12:55:12.265:   "d": {
12:55:12.265:     "requestId": "5c3cbc12-438e-4e52-8438-9a1c633ceb0b",
12:55:12.265:     "requestStatus": {
12:55:12.265:       "code": 100,
12:55:12.265:       "result": true
12:55:12.265:     },
12:55:12.265:     "requestType": "GetStreamStatus",
12:55:12.265:     "responseData": {
12:55:12.265:       "outputActive": false,
12:55:12.265:       "outputBytes": 0,
12:55:12.265:       "outputCongestion": 0.0,                                
**12:55:12.265:       "outputDuration": 0,**
12:55:12.265:       "outputReconnecting": false,
12:55:12.265:       "outputSkippedFrames": 0,
12:55:12.265:       "outputTimecode": "00:00:00.000",
12:55:12.265:       "outputTotalFrames": 0
12:55:12.265:     }
12:55:12.265:   },
12:55:12.265:   "op": 7
12:55:12.265: }

**Comment by tinodo** [comment] 2023-10-15 08:07
I will check it out shortly. See how we fix this...

**Comment by tinodo** [comment] 2023-10-15 09:08
It appears that the OBS Websockets component is not adhere to it's on specs.
According to [the protocol definition](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md) indeed, the OuputCongestion should be a number and not be null. But apparently it is.
Easiest way to 'fix' the issue is to make the property nullable. The other is to use a custom converter.
I will create a custom converter.

It will be fixed in 1.2.1

**Comment by Parfaitomcat** [comment] 2023-10-15 11:45
Thank you for your prompt correction.
It is true that OBS-WebSocket's JSON syntax did not satisfy the protocol definition.
However, I believe that OBS-WebSocket is just converting the information it gets from OBS into JSON syntax, and that OBS is probably passing null to OBS-WebSocket.

**Comment by Parfaitomcat** [comment] 2023-10-15 11:50
Please Close this issue

**Closed** 2023-10-15 12:07 UTC
Labels: bug
